version: "3"

services:
  api-service:
    build: "./api"
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "8005:8005"
    networks:
      - auth-network
    depends_on:
      - db-service

  db-service:
    image: mongo:3.6.19-xenial
    ports:
      - "2720:27017"
    networks:
      - auth-network
    volumes:
      - db-data:/data/db

networks:
  auth-network:
    driver: bridge
volumes:
  db-data:
    driver: local
