# FROM node:10
# # USER node

# WORKDIR /usr/src/app

# COPY ./package.json ./

# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD [ "npm", "start" ]

# stage 1
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_PORT=91
ENV REACT_APP_WHKEY=wh2
COPY . /app
RUN npm cache clean --force
# RUN npm ci --loglevel verbose
RUN npm ci
RUN npm run build

# # stage 2
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 90
CMD ["nginx", "-g", "daemon off;"]
# CMD [ "npm", "start" ]