version: "3"

services:
  app-service:
    build: "./app"
    volumes: 
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports: 
      - "3005:3000"
    networks:
      - wh1-network

  api-service:
    build: './api'
    volumes: 
      - ./api:/usr/src/app
      - /usr/src/api/node_modules
    ports: 
      - "8005:8005"
    networks:
      - wh1-network
    depends_on:
      - db-service
    


  db-service:
    image: mongo:3.6.19-xenial
    ports: 
      - "2720:27017"
    networks:
      - wh1-network
    volumes:
      - db-data:/data/db

networks:
  wh1-network:
    driver: bridge
volumes:
  db-data:
    driver: local