FROM node:10
# USER node

WORKDIR /usr/src/app

ENV REACT_APP_PORT=90
ENV REACT_APP_WHKEY=wh1
ENV REACT_APP_WHNAME="Magazyn 1 Rzeszów"

COPY ./package.json ./

RUN npm install -g nodemon

RUN npm install

#COPY . .
COPY . .

EXPOSE 8005

# CMD [ "nodemon" ]
CMD [ "npm", "run", "start.dev" ]


