services:
  pgdb:
    image: postgres
    volumes:
      - ./productsdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "products"
    networks:
      - products

  productsapp:
    build: './app'
    depends_on:
      - pgdb
    volumes: 
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8123:3000"
    restart: always
    depends_on:
      - pgdb
    networks:
      products:
      wspolna:
        ipv4_address: '10.1.0.204'
        aliases:
          - productsapi
        
volumes:
  productsdata: {}

networks:
  products:    
  wspolna:
    name: wspolna
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24